name: msft-defender-image-scan

on:
  push:
    branches:
      - 'feat/defender-acr'
      # - 'dev'
      # - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    name: Build and Scan Image
    env:
      IMAGE_NAME: nodejsdemo.azurecr.io/azure-nodejs-demo
      IMAGE_TAG: defender-scan # static for now b/c Azure Pipelines handles dev lifecycle for now.
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: npm install and build
        run: |
          npm ci
          npm run compile-sass

      - name: Build and tag Image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - uses: Azure/container-scan@v0
        name: Scan image for vulnerabilities
        id: container-scan
        with:
          image-name: $IMAGE_NAME:$IMAGE_TAG
          severity-threshold: WARN

# For details, see
# https://docs.microsoft.com/en-us/azure/defender-for-cloud/defender-for-container-registries-cicd
